config/routes.rb
Rails.application.routes.draw do
  

  resources :classrooms

  resources :courses

  resources :students

  root 'home#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base

  belongs_to :student
  belongs_to :course

  before_save :add_entry_at

  validates :student_id, :course_id, presence: true

  def add_entry_at
  	self.entry_at = Time.now
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :classrooms

	validates :status, numericality: { only_integer: true }
	validates :name, :status, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :classrooms

	validates :status, :register_number , numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: 'Classroom was successfully created.' }
        format.json { render action: 'show', status: :created, location: @classroom }
      else
        format.html { render action: 'new' }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:entry_at, :student_id, :course_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/_form.html.erb
<%= simple_form_for(@classroom) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    	
    <%= f.association :student %>

    <%= f.association :course %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<h1>Editing classroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

app/views/classrooms/index.html.erb
<h1>Listing classrooms</h1>

<table>
  <thead>
    <tr>
      <th>Entry at</th>
      <th>Student</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= classroom.entry_at %></td>
        <td><%= classroom.student.name %></td>
        <td><%= classroom.course.name %></td>
        <td><%= link_to 'Show', classroom %></td>
        <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
        <td><%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classroom', new_classroom_path %>

app/views/classrooms/new.html.erb
<h1>New classroom</h1>

<%= render 'form' %>

<%= link_to 'Back', classrooms_path %>

app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entry at:</strong>
  <%= @classroom.entry_at %>
</p>

<p>
  <strong>Student:</strong>
  <%= @classroom.student.name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @classroom.course.name %>
</p>

<%= link_to 'Edit', edit_classroom_path(@classroom) %> |
<%= link_to 'Back', classrooms_path %>

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><%= course.status %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @course.status %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/home/index.html.erb
<div id="home-links">
	<a href="/students">Students</a>
	<a href="/courses">Courses</a>
	<a href="/classrooms">Classrooms</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/students/_form.html.erb
<%= simple_form_for(@student) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :register_number %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Register number</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.register_number %></td>
        <td><%= student.status %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Register number:</strong>
  <%= @student.register_number %>
</p>

<p>
  <strong>Status:</strong>
  <%= @student.status %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>